CREATE TABLE Items (
    ID INT PRIMARY KEY,
    Price DOUBLE NOT NULL,
    Type ENUM('FRUITS', 'VEGETABLES') NOT NULL,
    Name VARCHAR(250) NOT NULL,
    Quantity INT NOT NULL,
    BrandName VARCHAR(250) NOT NULL,
    isOrganic BOOLEAN,  
    ExpirationDate DATE,
    Status ENUM('AVAILABLE', 'UNAVAILABLE') NOT NULL,
    ImageURL VARCHAR(250)
);