CREATE TABLE Items (
    ID INT PRIMARY KEY,
    Price DOUBLE NOT NULL,
    Type VARCHAR(10) CHECK (Type IN ('FRUITS', 'VEGGIES')),
    Name VARCHAR(250) NOT NULL,
    Quantity INT NOT NULL,
    Status VARCHAR(15) CHECK (Status IN ('AVAILABLE', 'NOT AVAILABLE'))
);